
<template>
  <section v-if="authEnabled && !token" class="admin-login-page">
    <form class="admin-login-card" @submit.prevent="doLogin"><h1>若依管理后台</h1><p>跨境选品系统 · admin / admin</p><label>账号<input v-model="login.username" /></label><label>密码<input type="password" v-model="login.password" /></label><button>登录</button><p v-if="message" class="notice">{{ message }}</p></form>
  </section>
  <section v-else class="ruoyi-layout">
    <aside class="ruoyi-sidebar"><div class="ruoyi-logo">RuoYi Admin</div><nav><button v-for="menu in flatMenus" :key="menu.menuKey" :class="['ruoyi-menu', activeMenu===menu.menuKey?'active':'', menu.parentId===0?'root':'child']" @click="selectMenu(menu)"><span>{{ menu.parentId===0?'▸':'•' }}</span>{{ menu.title }}</button></nav></aside>
    <main class="ruoyi-main">
      <header class="ruoyi-topbar"><div><strong>{{ activeTitle }}</strong><small>首页 / {{ activeTitle }}</small></div><div class="ruoyi-user"><select v-model="currentTenant"><option value="*">全部租户</option><option v-for="t in tenants" :key="t.tenantId" :value="t.tenantId">{{ t.tenantName }}</option></select><span>{{ profile?.nickname }}({{ profile?.tenantId }})</span><button class="ghost" @click="logout">退出</button></div></header>
      <div class="ruoyi-tags"><span>首页</span><span>{{ activeTitle }}</span></div>
      <section v-if="activeMenu==='dashboard'" class="admin-panel"><h2>工作台</h2><div class="admin-kpis"><article><span>租户</span><b>{{ tenants.length }}</b></article><article><span>用户</span><b>{{ users.length }}</b></article><article><span>角色</span><b>{{ roles.length }}</b></article><article><span>菜单</span><b>{{ flatMenus.length }}</b></article></div><p class="muted">核心若依管理闭环已启用：租户、用户、角色、菜单、字典、参数、日志、选品配置和报表管理。</p></section>

      <CrudPage v-if="activeMenu==='users'" title="用户管理" :rows="users" :columns="userColumns" :fields="userFields" :empty="emptyUser" @save="saveUser" @delete="deleteUser" />
      <section v-if="activeMenu==='roles'" class="admin-panel"><div class="crud-head"><h2>角色管理</h2><button @click="editingRole={id:0,tenantId:'default',roleKey:'',roleName:'',status:'enabled',menuKeys:[],remark:''}">新增</button></div><AdminDataTable :rows="roles" :columns="roleColumns" actions @edit="editingRole={...$event,menuKeys:[...($event.menuKeys||[])]}" @delete="deleteRole"/><AdminModalForm v-if="editingRole" title="角色表单" :model="editingRole" :fields="roleFields" @save="saveRole" @cancel="editingRole=null"><template #default="{draft}"><label>菜单权限<div class="check-grid"><label v-for="m in flatMenus" :key="m.menuKey"><input type="checkbox" :value="m.menuKey" v-model="draft.menuKeys"/>{{ m.title }}</label></div></label></template></AdminModalForm></section>
      <CrudPage v-if="activeMenu==='menus'" title="菜单管理" :rows="flatMenus" :columns="menuColumns" :fields="menuFields" :empty="emptyMenu" @save="saveMenu" @delete="deleteMenu" />
      <CrudPage v-if="activeMenu==='dict'" title="字典类型" :rows="dictTypes" :columns="dictTypeColumns" :fields="dictTypeFields" :empty="emptyDictType" @save="saveDictType" @delete="deleteDictType"><template #extra><h3>字典数据</h3><AdminDataTable :rows="dictData" :columns="dictDataColumns" actions @edit="editingDictData={...$event}" @delete="deleteDictData"/><button @click="editingDictData={id:0,tenantId:'default',dictType:'sys_normal_disable',dictLabel:'',dictValue:'',sortOrder:1,status:'enabled',remark:''}">新增字典数据</button><AdminModalForm v-if="editingDictData" title="字典数据" :model="editingDictData" :fields="dictDataFields" @save="saveDictData" @cancel="editingDictData=null"/></template></CrudPage>
      <CrudPage v-if="activeMenu==='configs'" title="参数配置" :rows="configs" :columns="configColumns" :fields="configFields" :empty="emptyConfig" @save="saveConfig" @delete="deleteConfig" />
      <section v-if="activeMenu==='logs'" class="admin-panel"><h2>操作日志</h2><AdminDataTable :rows="operLogs" :columns="operLogColumns"/><h2>登录日志</h2><AdminDataTable :rows="loginLogs" :columns="loginLogColumns"/></section>

      <section v-if="activeMenu==='sources'" class="admin-panel"><h2>数据源配置</h2><SettingsForm v-if="settings" :settings="settings" section="sources" @save="saveSettings"/><h3>接入状态</h3><div class="source-list"><article v-for="source in sources" :key="source.name"><strong>{{ source.name }}</strong><span :class="source.configured?'ok':'warn'">{{ source.configured?'已配置':'未配置' }}</span><p>{{ source.useCase }}</p><a :href="source.docsUrl" target="_blank">查看文档</a><small>{{ source.note }}</small></article></div></section>
      <CrudPage v-if="activeMenu==='markets'" title="市场配置" :rows="markets" :columns="marketColumns" :fields="marketFields" :empty="emptyMarket" @save="saveMarket" />
      <CrudPage v-if="activeMenu==='categories'" title="品类配置" :rows="categories" :columns="categoryColumns" :fields="categoryFields" :empty="emptyCategory" @save="saveCategory" />
      <section v-if="activeMenu==='schedules'" class="admin-panel"><h2>采集频率配置</h2><SettingsForm v-if="settings" :settings="settings" section="schedule" @save="saveSettings"/></section>
      <section v-if="activeMenu==='dailyReports'" class="admin-panel"><h2>日报记录</h2><AdminDataTable :rows="reports" :columns="reportColumns"/></section>
      <section v-if="activeMenu==='productPool'" class="admin-panel"><h2>商品池</h2><AdminDataTable :rows="productPool" :columns="productColumns"/></section>
      <p v-if="message" class="notice floating-notice">{{ message }}</p>
    </main>
  </section>
</template>

<script setup>
import { computed, defineComponent, h, onMounted, reactive, ref, watch } from 'vue';
import { api, joinText, splitText } from '../lib.js';
import AdminDataTable from './AdminDataTable.vue';
import AdminModalForm from './AdminModalForm.vue';
const token=ref(localStorage.getItem('adminToken')||''); const login=reactive({username:'admin',password:'admin'}); const message=ref(''); const currentTenant=ref('*'); const authEnabled=ref(null);
const profile=ref(null), menus=ref([]), users=ref([]), roles=ref([]), tenants=ref([]), dictTypes=ref([]), dictData=ref([]), configs=ref([]), operLogs=ref([]), loginLogs=ref([]), markets=ref([]), categories=ref([]), settings=ref(null), sources=ref([]), reports=ref([]);
const activeMenu=ref('dashboard'); const editingRole=ref(null), editingDictData=ref(null);
const flatMenus=computed(()=>flatten(menus.value)); const activeTitle=computed(()=>flatMenus.value.find(m=>m.menuKey===activeMenu.value)?.title||'工作台'); const productPool=computed(()=>(reports.value[0]?.products||[]).map(p=>({...p,rank:'#'+p.rank})));
function flatten(items){return items.flatMap(m=>[m,...(m.children?flatten(m.children):[])]);} function removeTenant(items){return (items||[]).filter(m=>m.menuKey!=='tenants').map(m=>({...m,children:removeTenant(m.children)}));} function tenantParam(){return currentTenant.value==='*'?'*':currentTenant.value;} async function adminApi(path,o={}){return api(path,{...o,headers:{...(o.headers||{}),Authorization:`Bearer ${token.value}`}})}
async function doLogin(){try{const r=await api('/admin/login',{method:'POST',body:JSON.stringify(login)});token.value=r.token;localStorage.setItem('adminToken',r.token);await loadAll();}catch(e){message.value='账号或密码错误';}}
function logout(){localStorage.removeItem('adminToken'); token.value='';} function selectMenu(m){if(m.component!=='Layout')activeMenu.value=m.menuKey;}
async function loadAll(){const status=await api('/admin/auth/status'); authEnabled.value=status.enabled; if(status.enabled&&!token.value)return; const [p,m,t,u,r,dt,dd,cfg,ol,ll,ma,ca,s,ds,rs]=await Promise.all([adminApi('/admin/profile'),adminApi('/admin/menus'),adminApi('/admin/tenants'),adminApi('/admin/users'),adminApi('/admin/roles'),adminApi('/admin/dict-types'),adminApi('/admin/dict-data'),adminApi('/admin/configs'),adminApi('/admin/oper-logs'),adminApi('/admin/login-logs'),adminApi('/admin/markets'),adminApi('/admin/categories'),adminApi('/admin/settings'),api('/datasources'),api('/reports')]); profile.value=p; menus.value=removeTenant(m); tenants.value=t; users.value=u; roles.value=r; dictTypes.value=dt; dictData.value=dd; configs.value=cfg; operLogs.value=ol; loginLogs.value=ll; markets.value=ma; categories.value=ca; settings.value=s; sources.value=ds; reports.value=rs;}
watch(currentTenant, async()=>{ if(!authEnabled.value || token.value){ users.value=await adminApi('/admin/users?tenantId='+tenantParam()); roles.value=await adminApi('/admin/roles?tenantId='+tenantParam()); markets.value=await adminApi('/admin/markets?tenantId='+tenantParam()); categories.value=await adminApi('/admin/categories?tenantId='+tenantParam()); }});
async function saveSettings(v){settings.value=await adminApi('/admin/settings',{method:'PUT',body:JSON.stringify(v)}); message.value='配置已保存';}
const crud = (base, target) => ({ save: async row => { await adminApi(row.id?`${base}/${row.id}`:base,{method:row.id?'PUT':'POST',body:JSON.stringify(row)}); target.value=await adminApi(base+(base.includes('?')?'':'') ); message.value='保存成功'; }, del: async row => { if(!row.id)return; await adminApi(`${base}/${row.id}`,{method:'DELETE'}); target.value=await adminApi(base); message.value='删除成功'; }});
async function saveTenant(row){await adminApi(row.id?`/admin/tenants/${row.id}`:'/admin/tenants',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});tenants.value=await adminApi('/admin/tenants');} async function deleteTenant(row){await adminApi(`/admin/tenants/${row.id}`,{method:'DELETE'});tenants.value=await adminApi('/admin/tenants');}
async function saveUser(row){await adminApi(row.id?`/admin/users/${row.id}`:'/admin/users',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});users.value=await adminApi('/admin/users?tenantId='+tenantParam());} async function deleteUser(row){await adminApi(`/admin/users/${row.id}`,{method:'DELETE'});users.value=await adminApi('/admin/users?tenantId='+tenantParam());}
async function saveRole(row){await adminApi(row.id?`/admin/roles/${row.id}`:'/admin/roles',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});editingRole.value=null;roles.value=await adminApi('/admin/roles?tenantId='+tenantParam());} async function deleteRole(row){await adminApi(`/admin/roles/${row.id}`,{method:'DELETE'});roles.value=await adminApi('/admin/roles?tenantId='+tenantParam());}
async function saveMenu(row){await adminApi(row.id?`/admin/menus/${row.id}`:'/admin/menus',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});menus.value=await adminApi('/admin/menus');} async function deleteMenu(row){await adminApi(`/admin/menus/${row.id}`,{method:'DELETE'});menus.value=await adminApi('/admin/menus');}
async function saveDictType(row){await adminApi(row.id?`/admin/dict-types/${row.id}`:'/admin/dict-types',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});dictTypes.value=await adminApi('/admin/dict-types?tenantId='+tenantParam());} async function deleteDictType(row){await adminApi(`/admin/dict-types/${row.id}`,{method:'DELETE'});dictTypes.value=await adminApi('/admin/dict-types?tenantId='+tenantParam());}
async function saveDictData(row){await adminApi(row.id?`/admin/dict-data/${row.id}`:'/admin/dict-data',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});editingDictData.value=null;dictData.value=await adminApi('/admin/dict-data?tenantId='+tenantParam());} async function deleteDictData(row){await adminApi(`/admin/dict-data/${row.id}`,{method:'DELETE'});dictData.value=await adminApi('/admin/dict-data?tenantId='+tenantParam());}
async function saveConfig(row){await adminApi(row.id?`/admin/configs/${row.id}`:'/admin/configs',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});configs.value=await adminApi('/admin/configs?tenantId='+tenantParam());} async function deleteConfig(row){await adminApi(`/admin/configs/${row.id}`,{method:'DELETE'});configs.value=await adminApi('/admin/configs?tenantId='+tenantParam());}
async function saveMarket(row){await adminApi(row.id?`/admin/markets/${row.id}`:'/admin/markets',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});markets.value=await adminApi('/admin/markets?tenantId='+tenantParam());}
async function saveCategory(row){await adminApi(row.id?`/admin/categories/${row.id}`:'/admin/categories',{method:row.id?'PUT':'POST',body:JSON.stringify(row)});categories.value=await adminApi('/admin/categories?tenantId='+tenantParam());}
onMounted(()=>loadAll().catch(e=>message.value=e.message));
const statusOpts=['enabled','disabled']; const tenantOpts=computed(()=>tenants.value.map(t=>({value:t.tenantId,label:t.tenantName}))); const roleOpts=computed(()=>roles.value.map(r=>({value:r.roleKey,label:r.roleName}))); const menuOpts=computed(()=>[{value:0,label:'根菜单'},...flatMenus.value.map(m=>({value:m.id,label:m.title}))]); const dictTypeOpts=computed(()=>dictTypes.value.map(d=>({value:d.dictType,label:d.dictName}))); const marketOpts=computed(()=>markets.value.map(m=>({value:m.marketKey,label:m.marketName})));
const tenantColumns=[['tenantId','租户标识'],['tenantName','租户名称'],['contactUser','联系人'],['packageName','套餐'],['status','状态']].map(([key,label])=>({key,label})); const userColumns=[['tenantId','租户'],['username','用户名'],['nickname','昵称'],['roleKey','角色'],['status','状态'],['email','邮箱'],['phone','手机']].map(([key,label])=>({key,label})); const roleColumns=[['tenantId','租户'],['roleKey','标识'],['roleName','名称'],['status','状态'],['menuKeys','菜单权限']].map(([key,label])=>({key,label})); const menuColumns=[['id','ID'],['parentId','父级'],['title','菜单'],['menuKey','标识'],['path','路径'],['permission','权限'],['sortOrder','排序'],['status','状态']].map(([key,label])=>({key,label}));
const dictTypeColumns=[['tenantId','租户'],['dictName','名称'],['dictType','类型'],['status','状态'],['remark','备注']].map(([key,label])=>({key,label})); const dictDataColumns=[['tenantId','租户'],['dictType','类型'],['dictLabel','标签'],['dictValue','值'],['sortOrder','排序'],['status','状态']].map(([key,label])=>({key,label})); const configColumns=[['tenantId','租户'],['configName','名称'],['configKey','键'],['configValue','值'],['systemBuiltin','内置'],['remark','备注']].map(([key,label])=>({key,label}));
const marketColumns=[['tenantId','租户'],['marketKey','标识'],['marketName','名称'],['region','区域'],['enabled','启用'],['note','说明']].map(([key,label])=>({key,label})); const categoryColumns=[['tenantId','租户'],['categoryName','品类'],['marketKey','市场'],['enabled','启用'],['keywords','关键词']].map(([key,label])=>({key,label})); const operLogColumns=[['createdAt','时间'],['tenantId','租户'],['username','用户'],['module','模块'],['action','操作'],['status','状态'],['message','消息']].map(([key,label])=>({key,label})); const loginLogColumns=[['createdAt','时间'],['tenantId','租户'],['username','用户'],['ipaddr','IP'],['status','状态'],['message','消息']].map(([key,label])=>({key,label})); const reportColumns=[['reportDate','日期'],['title','标题'],['sourceMode','数据源'],['summary','摘要']].map(([key,label])=>({key,label})); const productColumns=[['rank','排名'],['productNameCn','商品'],['category','品类'],['heatScore','热度'],['estimatedProfitCny','利润']].map(([key,label])=>({key,label}));
const tenantFields=computed(()=>[{key:'tenantId',label:'租户标识'},{key:'tenantName',label:'租户名称'},{key:'contactUser',label:'联系人'},{key:'contactPhone',label:'联系电话'},{key:'packageName',label:'套餐'},{key:'status',label:'状态',type:'select',options:statusOpts},{key:'remark',label:'备注'}]); const userFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'username',label:'用户名'},{key:'password',label:'密码'},{key:'nickname',label:'昵称'},{key:'roleKey',label:'角色',type:'select',options:roleOpts.value},{key:'status',label:'状态',type:'select',options:statusOpts},{key:'email',label:'邮箱'},{key:'phone',label:'手机'}]); const roleFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'roleKey',label:'角色标识'},{key:'roleName',label:'角色名称'},{key:'status',label:'状态',type:'select',options:statusOpts},{key:'remark',label:'备注'}]); const menuFields=computed(()=>[{key:'parentId',label:'父级菜单',type:'select',options:menuOpts.value},{key:'menuKey',label:'菜单标识'},{key:'title',label:'菜单名称'},{key:'icon',label:'图标'},{key:'path',label:'路由'},{key:'component',label:'组件'},{key:'permission',label:'权限标识'},{key:'sortOrder',label:'排序',type:'number'},{key:'status',label:'状态',type:'select',options:statusOpts}]);
const dictTypeFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'dictName',label:'字典名称'},{key:'dictType',label:'字典类型'},{key:'status',label:'状态',type:'select',options:statusOpts},{key:'remark',label:'备注'}]); const dictDataFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'dictType',label:'字典类型',type:'select',options:dictTypeOpts.value},{key:'dictLabel',label:'标签'},{key:'dictValue',label:'值'},{key:'sortOrder',label:'排序',type:'number'},{key:'status',label:'状态',type:'select',options:statusOpts},{key:'remark',label:'备注'}]); const configFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'configName',label:'参数名称'},{key:'configKey',label:'参数键'},{key:'configValue',label:'参数值'},{key:'systemBuiltin',label:'系统内置',type:'checkbox'},{key:'remark',label:'备注'}]); const marketFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'marketKey',label:'市场标识'},{key:'marketName',label:'市场名称'},{key:'region',label:'区域'},{key:'enabled',label:'启用',type:'checkbox'},{key:'note',label:'说明'}]); const categoryFields=computed(()=>[{key:'tenantId',label:'租户',type:'select',options:tenantOpts.value},{key:'categoryName',label:'品类名称'},{key:'marketKey',label:'市场',type:'select',options:marketOpts.value},{key:'enabled',label:'启用',type:'checkbox'},{key:'keywords',label:'关键词'},{key:'note',label:'说明'}]);
const emptyTenant={id:0,tenantId:'',tenantName:'',contactUser:'',contactPhone:'',packageName:'基础套餐',status:'enabled',remark:''}; const emptyUser={id:0,tenantId:'default',username:'',password:'admin',nickname:'',roleKey:'operator',status:'enabled',email:'',phone:''}; const emptyMenu={id:0,parentId:0,menuKey:'',title:'',icon:'',path:'',component:'',permission:'',sortOrder:99,status:'enabled'}; const emptyDictType={id:0,tenantId:'default',dictName:'',dictType:'',status:'enabled',remark:''}; const emptyConfig={id:0,tenantId:'default',configName:'',configKey:'',configValue:'',systemBuiltin:false,remark:''}; const emptyMarket={id:0,tenantId:'default',marketKey:'',marketName:'',region:'',enabled:false,note:''}; const emptyCategory={id:0,tenantId:'default',categoryName:'',marketKey:'jp',enabled:true,keywords:'',note:''};
const CrudPage=defineComponent({components:{AdminDataTable,AdminModalForm},props:['title','rows','columns','fields','empty'],emits:['save','delete'],data(){return{editing:null}},template:`<section class="admin-panel"><div class="crud-head"><h2>{{title}}</h2><button @click="editing={...empty}">新增</button></div><slot name="before"></slot><AdminDataTable :rows="rows" :columns="columns" actions @edit="editing={...$event}" @delete="$emit('delete',$event)"/><slot name="extra"></slot><AdminModalForm v-if="editing" :title="title+'表单'" :model="editing" :fields="fields" @save="$emit('save',$event);editing=null" @cancel="editing=null"/></section>`});
const SettingsForm=defineComponent({props:['settings','section'],emits:['save'],setup(props,{emit}){const draft=reactive(JSON.parse(JSON.stringify(props.settings)));function save(){emit('save',draft)}return{draft,save,joinText,splitText}},template:`<section class="settings-form"><template v-if="section==='sources'"><label>国外检索数据源<textarea :value="joinText(draft.foreignSources)" @input="draft.foreignSources=splitText($event.target.value)" /></label><label>国内检索数据源<textarea :value="joinText(draft.domesticSources)" @input="draft.domesticSources=splitText($event.target.value)" /></label></template><template v-else><label>检索频率 Cron<input v-model="draft.frequencyCron" /></label><label>每日报表商品数<input type="number" v-model.number="draft.maxProducts" /></label><label>日元汇率<input type="number" step="0.001" v-model="draft.jpyCnyRate" /></label><label>默认物流成本<input type="number" v-model="draft.defaultShippingCny" /></label><label class="check"><input type="checkbox" v-model="draft.smartMode" />启用智能模式</label></template><button @click="save">保存配置</button></section>`});
</script>
